# Generated by Django 3.1.4 on 2020-12-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='none', max_length=255)),
                ('middlename', models.CharField(default='none', max_length=255)),
                ('lastname', models.CharField(default='none', max_length=255)),
            ],
        ),
    ]
