# Generated by Django 3.1.4 on 2020-12-31 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
