# Generated by Django 3.1.4 on 2021-01-05 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0003_auto_20201231_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTypeMaster',
            fields=[
                ('UserTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('UserType', models.CharField(max_length=255)),
                ('CreateAt', models.DateTimeField(auto_now_add=True)),
                ('ModifiedAt', models.DateTimeField(auto_now=True)),
                ('IsActive', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(help_text='Enter User Name: ', max_length=25)),
                ('UserPassword', models.CharField(max_length=20)),
                ('UserEmail', models.EmailField(max_length=25, unique=True)),
                ('UserMobile', models.BigIntegerField()),
                ('UserAddress', models.CharField(blank=True, default='None', max_length=255, null=True)),
                ('CreateAt', models.DateTimeField(auto_now_add=True)),
                ('ModifiedAt', models.DateTimeField(auto_now=True)),
                ('IsActive', models.BooleanField(default=0)),
                ('UserTypeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.usertypemaster')),
            ],
            options={
                'ordering': ['UserName'],
            },
        ),
    ]
